"""Google OAuth authentication."""

from __future__ import annotations

from typing import Any

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

from .config import Settings


SCOPES = [
    "https://www.googleapis.com/auth/gmail.readonly",
    "https://www.googleapis.com/auth/spreadsheets",
]


def build_services(settings: Settings) -> tuple[Any, Any]:
    credentials: Credentials | None = None

    if settings.token_file.exists():
        try:
            credentials = Credentials.from_authorized_user_file(
                str(settings.token_file), SCOPES
            )
        except (ValueError, OSError):
            credentials = None

    if credentials and credentials.expired and credentials.refresh_token:
        try:
            credentials.refresh(Request())
        except Exception:
            credentials = None

    if not credentials or not credentials.valid:
        if not settings.credentials_file.exists():
            raise FileNotFoundError(
                f"OAuth credentials file not found: {settings.credentials_file}"
            )

        flow = InstalledAppFlow.from_client_secrets_file(
            str(settings.credentials_file), SCOPES
        )

        print(
            "\nAuthorization is required.\n"
            "Open only the URL generated by this run and approve BOTH "
            "Gmail and Google Sheets permissions.\n"
        )

        try:
            credentials = flow.run_local_server(
                host="127.0.0.1",
                port=8765,
                open_browser=False,
                prompt="consent",
                include_granted_scopes="true",
            )
        except Warning as exc:
            raise PermissionError(
                "Google did not grant every requested permission. "
                "Delete token.json and authorize again, selecting both "
                "Gmail and Google Sheets."
            ) from exc

        if not credentials.has_scopes(SCOPES):
            raise PermissionError(
                "Authorization is missing Gmail or Sheets access. "
                "Delete token.json and authorize again."
            )

        settings.token_file.parent.mkdir(parents=True, exist_ok=True)
        settings.token_file.write_text(
            credentials.to_json(), encoding="utf-8"
        )
        print(f"Authorization saved to {settings.token_file}")

    gmail = build(
        "gmail", "v1", credentials=credentials, cache_discovery=False
    )
    sheets = build(
        "sheets", "v4", credentials=credentials, cache_discovery=False
    )
    return gmail, sheets
